#!/usr/bin/python
#

#
# Copyright (C) 2008 Pieter Palmers
#               2009 Arnold Krilles
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Report build-time libraries.
# Called by SConstruct to generate static_info.txt.
#

import ffado_diag_helpers

welcome_msg = """

FFADO static diagnostic utility
============================
(C) 2008 Pieter Palmers
(C) 2009 Arnold Krille

"""

## main program
if __name__== '__main__':

    print(welcome_msg)

    ffado_diag_helpers.parse_command_line()

    print("=== CHECK ===")

    ffado_diag_helpers.check_libraries()
