.TH FFADO-MIXER 1 09-Jan-2017 "ffado-mixer"
.SH NAME
ffado-mixer \- a graphical front-end for the FFADO mixer DBus controls
exposed by ffado-dbus-server.
.SH SYNOPSIS
.BI "ffado-mixer [options]"
.sp
Available options:
.B "[\-b]"
.sp
.SH DESCRIPTION
.B ffado-mixer
presents a graphical application allowing a FFADO device to be controlled. 
The extent of the control is determined by the level of support for the
device in FFADO and in 
.B ffado-dbus-server.
Typical controls offered by
.B ffado-mixer
include faders for the on-board mixer, phantom power control, mode switches
and so on.
.SH "OPTIONS"
.TP
.B "\-b"
Do not query ffado-dbus-server for an active interface.  Instead, create
an instance of a mixer for every supported interface as defined in FFADO's
"configuration" file with stubs providing placeholder values in place of
settings obtained from the interface.  This is primarily to assist with
debugging.
.SH "SEE ALSO"
.BR ffado-dbus-server (1)
